/*
	RVD_Vertex
	record the intersection Vertex and normal Vertex
*/

#ifndef H_RVD_VERTEX_H
#define H_RVD_VERTEX_H

#include "Common.h"
#include "math_3d.h"

namespace P_RVD
{
	/*
		defien the vertex type
		symbolic
		*/
	enum VertexType
	{
		VertexType1,
		VertexType2,
		VertexType3
	};

	/*
		define the Edge type

		the edge generated by this vertex and the previous one
		Original : this edge is already existed
		Intersection : this edge is new added
		*/
	enum EdgeType
	{
		Virtual = 0,
		Original = 1,
		Intersection = 2

		
	};

	class Vertex
	{
	public:

		/*
			Create a new Vertex
			used when create a vertex by an intersection
		*/
		Vertex(
			Vector3d _v,
			double _w,
			EdgeType _et,
			VertexType _vt,
			signed_t_index _f,
			signed_t_index _s
			) : 
			m_position(_v),
			m_weight(_w),
			m_vertex_type(_vt),
			m_edge_type(Original),
			m_facet(_f),
			m_seed(_s){
		};

		/*
		Create a new Vertex
		used when create a vertex when it is already existed
		*/
		Vertex(
			Vector3d _v,
			double _w,
			signed_t_index _f
			) :
			m_position(_v),
			m_weight(_w),
			m_edge_type(Original),
			m_facet(_f),
			m_seed(-1){
		};

		/*
			Create a vertex without Initialization
		*/
		Vertex() :
			m_position(Vector3d(0.0, 0.0, 0.0)),
			m_weight(1.0),
			m_facet(-1),
			m_seed(-1),
			m_edge_type(Virtual){
		}

		/*
			get the position of this vertex
		*/
		const Vector3d getPosition() const
		{
			return m_position;
		}

		/*
			use a vector3d to set the position of the vertex
		*/
		void setPosition(const Vector3d _position)
		{
			m_position = _position;
		}

		/*
			get the weight of this vertex
		*/
		double getWeight(){ return m_weight; }

		/*
			set the value of the weight of the vertex
		*/
		void setWeight(double _w)
		{
			m_weight = _w;
		}

		/*
			get the relative seed index
		*/
		signed_t_index getSeed(){ return m_seed; }

		/*
			set the relative seed
		*/
		void setSeed(signed_t_index _s)
		{
			m_seed = _s;
		}

		/*
			get the relative facet
		*/
		signed_t_index getFacet(){ return m_facet; }

		/*
			set the relative facet
		*/
		void setFacet(signed_t_index _f)
		{
			m_facet = _f;
		}

		/*
			get the type of the vertex
		*/
		VertexType getVertexType(){ return m_vertex_type; }

		/*
			set the vertex type
		*/
		void setVertexTpye(VertexType _vt)
		{
			m_vertex_type = _vt;
		}

		/*
			get the edge type
		*/
		EdgeType getEdgeType(){ return m_edge_type; }

		/*
			set the type of edge
		*/
		void setEdgeType(EdgeType _et)
		{
			m_edge_type = _et;
		}


		void clear()
		{
			m_edge_type = Virtual;
		}

		bool check_vertex()
		{
			if (m_edge_type == Virtual)
				return false;
			return true;
		}
	protected:
		VertexType m_vertex_type;
		EdgeType m_edge_type;

		Vector3d m_position;
		double m_weight;

		/*
			identify which facet this vertex is connected to
		*/
		signed_t_index m_facet;

		/*
			identify which seed is connected to

			if m_seed is negative, this vertex is an original vertex
			if m_seed is unsigned, this vertex is an intersection vertex
		*/
		signed_t_index m_seed;
	};

}
#endif /* H_RVD_VERTEX_H */